### ISSUE TITLE
An equivalent to WebkitGtk with Gecko

### ISSUE THREAD

**Issue by sergio-costas** [mozilla/platform-tilt#28]
Just a personal opinion, but having an equivalent to WebkitGtk that uses Gecko/SpiderMonkey, with the same simplicity to use it, would allow a big impulse (the documentation about how to embed Gecko seems to be very outdated). An example: some days ago I just needed a quick and dirty browser for a personal project, and was able to build one in less that 15 minutes and a fistful of lines; but, of course, with Webkit. Even more: having a common GObject interface, with the basic functions (open an URI, inserting Javascript in the page, reload...) would allow switching the web engine, even "on the fly".

**Comment by Mte90** [comment]
It isn't a new request, on Mozilla Connect the discussion it's there since some years 

* https://connect.mozilla.org/t5/ideas/create-an-alternative-to-electron/idi-p/268
* https://connect.mozilla.org/t5/ideas/ability-to-embed-gecko-as-an-alternative-to-chromium-embedding/idi-p/186

There is also the WebView W3C group https://www.w3.org/community/webview/

**Comment by kepstin** [comment]
This issue could be re-worded to be in line with the other entries on the page:

## Vendor: Mozilla

### No stable embedding API

Since Mozilla does not provide a stable embedding API for their browser engine, third party applications which want to build an application which either shows web content, or where the application itself is built with web technologies, cannot use the Mozilla platform. Applications have to use technologies from other vendors - and will often end up using embedding APIs provided by first-party vendors.

Apple, Google, and Microsoft all provide embedded web views that are available on their first-party platforms, based on [WebKit](https://developer.apple.com/documentation/webkit/wkwebview), [Chrome](https://developer.android.com/develop/ui/views/layout/webapps/webview), and [Edge](https://learn.microsoft.com/en-us/microsoft-edge/webview2/) respectively. WebKit (via e.g. [WPE WebKit](https://wpewebkit.org/) and [WebKitGTK](https://webkitgtk.org/)) and Google Chromium (via e.g. [CEF](https://bitbucket.org/chromiumembedded/cef/src/master/) and [Electron](https://www.electronjs.org/)) are both available to build applications using web technologies across multiple platforms.

**Comment by bgrins** [comment]
This repo catalogs self-preferencing behavior in operating systems, and is not the right forum to request features for Firefox (or Gecko).
