### ISSUE TITLE
PWAs only work in Chromium-based browsers on desktop

### ISSUE THREAD

**Issue by stuartmaxwell** [mozilla/platform-tilt#32]
To use PWAs on desktop, Mozilla forces users to use a Chromium-based browser. Mozilla should be called out for intentionally forcing users away from Firefox.

**Comment by Jaifroid** [comment]
Um, PWAs most certainly do work on Firefox Desktop, they just can't be installed. PWA = **Progressive** Web App, with the progressive part meaning that a well designed PWA should support the "next-best" API if a primary one is unsupported by the browser. If a particular PWA you use isn't supported on Firefox, it's because the devs of the PWA haven't tested it properly and provided fallbacks.

On Firefox desktop, PWAs can be bookmarked, and if they have offline support they'll work fully offline from the bookmark. It would be nice if Firefox had some kind of "pin site to desktop" or "pin to taskbar / dock", which would go a long way towards bridging the gap in installability. It wouldn't even require supporting the `onbeforeinstall` event.

**Comment by Mte90** [comment]
As I know in Firefox itself doesn't work pretty well with PWA, there are some tickets https://bugzilla.mozilla.org/buglist.cgi?quicksearch=progressive%20web%20app&list_id=16871650

Anyway there is MDN doc on how to install them https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Installing
There is also an extension with native support for desktop that implement it better https://github.com/filips123/PWAsForFirefox

**Comment by Jaifroid** [comment]
That extension looks really useful -- I'll check it out! Some of those tickets on bugzilla seem a bit minor. I develop a PWA and have had no complaints from users about how it works in Firefox, other than lack of support for the File System Access API (sort of overcome by Firefox's support of the Origin Private File System, but only sort of due to the measly disk space quota Firefox allows).

**Comment by bgrins** [comment]
This repo catalogs self-preferencing behavior in operating systems, and is not the right forum to request features for Firefox.
